pcdshub/pcdsutils

- pcdsutils/__init__.py
- pcdsutils/log.py
- pcdsutils/tests/test_logging.py
A preliminary implementation, with a bit of code borrowed from caproto (aka the project with the most effort put into logging).
Examples of what these dictionaries look like:
<details>
pcdsutils/tests/test_logging.py::test_log_warning_udp
```
{'exc_text': None,
'filename': 'test_logging.py',
'lineno': 57,
'msg': 'test1',
'pathname': '/Users/klauer/docs/Repos/pcdsutils/pcdsutils/tests/test_logging.py',
'schema': 'python-event-0',
'source': 'test_logging.test_log_warning_udp:57',
'versions': {'_csv': '1.0',
'_decimal': '1.70',
'_pytest': '5.3.4',
'argparse': '1.1',
'attr': '19.3.0',
'coverage': '5.0.3',
'coverage.jsonreport': '5.0.3',
'coverage.sqldata': '5.0.3',
'coverage.version': '5.0.3',
'coverage.xmlreport': '5.0.3',
'csv': '1.0',
'decimal': '1.70',
'importlib_metadata': '1.4.0', …
```
> ENH: add Python logger hook for PCDS-wide logging system

- pcdsutils/log.py
Closes #11 
Noted failing on conda-forge tests
Keys will change slightly, but that's not an issue for now. See: https://docs.python.org/3/library/platform.html#platform.uname
> REF: use portable platform.uname() to fix win32 support

- .pre-commit-config.yaml
- pcdsutils/release_notes.py
Closes #14 
Release notes utility converts from GitHub releases to `release_notes.rst` for documentation.
Requires pypandoc and requests, but I don't think we should add these to pcdsutils's requirements unless others do.
Also not adding this as a command-line entry for now. It can be invoked easily enough using `python -m pcdsutils.release_notes`
* Made sense to do this before releasing ads-ioc
With one release notes generation
> ENH: add release notes utility

- pcdsutils/ext_scripts.py
- pcdsutils/tests/test_ext_scripts.py
Move `pcdsdaq.ext_scripts` to `pcdsutils.ext_scripts` with no changes.
There is probably some cleanup to do here. I think we should do it in a follow-up PR to keep the change history clear.
In general, python wrappers for `engineering_tools`, `pds/tools` , and other shell scripts should be importable without importing pcdsdaq.
N/A, but the code did not reference anything in `pcdsdaq` so I expect it to work the same.
I haven't done this yet.
> ENH: transplant ext_scripts from pcdsdaq

- pcdsutils/ext_scripts.py
Follow-up to #22 where we clean up the module a bit by adding docstrings ~~and switching to the built-in `functools.lru_cache`~~
- The code is easier to follow now with the relevant docstrings.
- ~~Using built-ins is always preferred when they exist~~ it will require some refactoring to switch to using the built-in caching
Interactively + the tests still pass
Docstrings
> MNT: ext_scripts cleanup

- pcdsutils/requirements.py
Was:
```
Version mismatch:
TypeError: '<' not supported between instances of 'dict' and 'dict'
```
Is now:
```
:pcdsdevices klauer$ requirements-compare .
--- requirements.txt: host/build/run ---
Missing in pip:
- matplotlib-base
- numpy
Version mismatch:
- conda: bluesky>=1.6.4 pip: bluesky>=1.2.0
- conda: ophyd>=1.5.1 pip: ophyd>=1.2.0
- conda: pcdscalc>=0.2.0 pip: pcdscalc
- conda: pcdsutils>=0.4.0 pip: pcdsutils
- conda: pyepics>=3.4.2 pip: pyepics
- conda: pytmc>=2.7.0 pip: pytmc
```
> FIX: version difference display broken

- .pre-commit-config.yaml
- pcdsutils/log.py
- pcdsutils/utils.py
With `log_exception_to_central_server` now in hutch-python and lucid, it only made sense to bring it upstream to pcdsutils where the central logger lives.
The previous naming was a bit superfluous since now it belongs in the centralized-logging helper module, so I chose to just name it `log_exception`. Open to changing it, if you guys feel otherwise.
Contains the recent `stacklevel` option, of course, as well.
> ENH: add log_exception and related tools

- .gitignore
- .travis.yml
- conda-recipe/meta.yaml
- dev-requirements.txt
- pcdsutils/log.py
- pcdsutils/tests/test_ext_scripts.py
- pcdsutils/tests/test_logging.py
- Add a filter to demote the log level of https://github.com/bluesky/ophyd/blob/9e6c7de69a7bc6cc7e3b3c7273a5d3add9825513/ophyd/ophydobj.py#L466
- Refactor #37 such that these filters share common code, to avoid logic duplication
- Add option for demoting duplicates only vs all log messages
- Add counter for other tools to use to see how many log messages have been demoted
- The log message this targets is very likely to be a source of spam
- The configuration options give us choices for later when we apply these to hutch-python
- Ideas for using the counter: how many log messages were skipped during the scan? display the number of hidden messages in the prompt?
- Might be redundant with https://github.com/pcdshub/hutch-python/pull/298 but I think it's important to catch these messages …
> ENH: Add callback exception deduplication filter

- pcdsutils/ext_scripts.py
- pcdsutils/tests/test_ext_scripts.py
Wrap the engineering tools script `get_curr_exp`.
* It wasn't there, but we have a lesser version that should be replaced in hutch-python
* Some basic type hints
Test suite plus:
```
$ ipython -c "import pcdsutils.ext_scripts; print(pcdsutils.ext_scripts.get_current_experiment())"
xcsc00120
```
PR text
> ENH: get current experiment

- pcdsutils/log.py
- pcdsutils/tests/test_logging.py
Apply log level redundantly in demotion filter
The expected effect of demotion filter is to drop the log level, but the log level is checked before the filter is run, so if the log record would have been dropped by the log level then we need to apply it retroactively.
The behavior of modifying the record on the way through is still needed for the cases where we have e.g. a demotion filter on a logger with log level not set that needs to propagate debug-level messages to a root logger that has leveled handlers
Added tests that fail before my patch and pass afterwards
WIP
> BUG: prospective fix for demotion filter ignoring handler log level

- pcdsutils/ophyd.py
- pcdsutils/ophyd_helpers.py
- pcdsutils/tests/test_ophyd.py
- pcdsutils/type_hints.py
- requirements.txt
* Adds `no_device_lazy_load`:  Context manager which disables the ophyd.device.Device `lazy_wait_for_connection` behavior and later restore its value.
* Adds `subscription_context`:  Context manager which subscribes to a specific event from all provided objects, and unsubscribes after.
* Adds `subscription_context_device`:  Context manager which subscribes to a specific event from all matching signals on a device, and unsubscribes after.
* Adds `get_all_signals_from_device`: Gets all signals that match from a given device, with special lazy handling
* Adds `acquire_blocking` which subscribes to a signal for a period of time and returns all values acquired
* Adds `acquire_async` which does the same but for asyncio
* Adds `pcdsutils.type_hints` for common/reusable hints (considering to add …
> ENH: add ophyd helpers from typhos/atef

- pcdsutils/qt/lazy.py
Untested LazyWidget, borrowed/tweaked from https://github.com/pcdshub/typhos/pull/500
> ENH: add LazyWidget

- pcdsutils/profile.py
- pcdsutils/tests/dummy_submodule.py
- pcdsutils/tests/test_profile.py
Adjust the profile discovery mechanism so that it no longer skips classmethods and staticmethods. Both changes (getmembers, ismember) are needed.
Replicate the typhos PR mostly (https://github.com/pcdshub/typhos/pull/505), adding tests
closes #57 
closes #58 
Added tests, confirmed interactively that this reveals the pcdsdevices methods I was trying to see
Later in the release notes
> FIX: classmethods and staticmethods in profiler

- pcdsutils/import_timer.py
- pcdsutils/tests/test_import_timer.py
- setup.py
- build a table that shows which sub-imports take the most time when you do an import
- for a specific module, breakdown which submodules are taking up the most time
- for a specific import, trace where its being imported from
This is fairly accurate for the "time spent in this module" summaries and the import chaining, but has some inaccuracies with the "cumulative" timings that I don't want to rewrite the module to fix since that wasn't my main focus here. Namely, the true cumulative timing summary for a library may be split across the importtime output and may need a `max` at each split and a `sum` between splits but I've ignored that complexity entirely because I don't care about that number very much.
When you set up a single happi device, it takes a while just on imports.
I want to …
> ENH: import timing function using python built-in options

- pcdsutils/log.py
Don't log `NameError` to the centralized logging system.
`SyntaxError` is included for good measure, but we don't actually see it with IPython catching it first.
It's not useful for us
Closes #61 
Not tested
Issue + PR text
> FIX: don't log SyntaxError/NameError

- pcdsutils/log.py
Add `exc_filename` and `exc_line` to global log JSON.
Closes #63 
* Interactively with a script that raises in the main thread and a background thread
* In hutch-python
Issue and PR
Related but not dependent: https://github.com/pcdshub/hutch-python/pull/346
> ENH: log exception filename/line number

- .pre-commit-config.yaml
- conda-recipe/meta.yaml
- dev-requirements.txt
- docs-requirements.txt
- docs/Makefile
- docs/pre-release-notes.sh
- docs/release_notes.py
- docs/source/conf.py
- docs/source/index.rst
- docs/source/releases.rst
- docs/source/upcoming_changes.rst
- docs/source/upcoming_release_notes/51-add-get-info-json.rst
- docs/source/upcoming_release_notes/template-full.rst
- docs/source/upcoming_release_notes/template-short.rst
- docs/update_api_list.py
- pyproject.toml
* Add auto-generated API documentation and pre-release note scripts
* Unpin line-profiler for Python 3.11 support
There are no docs here!
Locally built docs
This is docs
> DOC: add API docs + pre-release note scripts

- pcdsutils/info.py
- pyproject.toml
* Add `pcdsutils-get-info-json` entrypoint (named as such to avoid a generic "get-info-json" binary in non-ECS installations; am willing to change after discussion). Name based on https://github.com/pcdshub/engineering_tools/blob/master/scripts/get_info
* #51 brought get-info-json into pcdsutils after a year of sitting idle
* This aims to make it useful or at least add notes about the weird parts previous reviewers found
Interactively
PR for now; dotfiles/confluence/sphinx later?
> ENH: add entrypoint for get-info-json

- .gitignore
- docs/source/upcoming_release_notes/80-enh_weakpartial.rst
- pcdsutils/qt/callbacks.py
- adds WeakPartialMethodSlot from Typhos
- added the callback args to the method call.
If you want to do use a partial in a callback, you should use this
Playing around with it in atef
This PR
> ENH: Add WeakPartialMethodSlot

- .github/PULL_REQUEST_TEMPLATE.md
- docs/source/upcoming_release_notes/81-enh_pydm_filter.rst
- pcdsutils/log.py
- pcdsutils/tests/test_logging.py
Add a filter for demoting this kind of error message from ERROR to DEBUG:
```
[2023-10-13 12:23:15,563] [ERROR   ] - Unable to remove connection for <PyDMChannel (ca://AT2L0:CALC:FILTER:02:Thickness)>
Traceback (most recent call last):
File "/cds/home/z/zlentz/pydev/pydm/widgets/channel.py", line 164, in disconnect
plugin.remove_connection(self, destroying=destroying)
File "/cds/home/z/zlentz/pydev/pydm/data_plugins/plugin.py", line 323, in remove_connection
self.connections[connection_id].deleteLater()
RuntimeError: wrapped C/C++ object of type Connection has been deleted
```
These errors are raised and logged upon closing PyDM here, during the cleanup: https://github.com/slaclab/pydm/blob/4354f306e0cae15375204536673b8c551a2d2b67/pydm/widgets/channel.py#L166
These are likely important to …
> ENH: add filter for demoting pydm at exit error spam

- docs/source/upcoming_release_notes/83-bug_weak_slot_disconn.rst
- pcdsutils/qt/callbacks.py
Keep a weakref to the signal owner and make sure it exists before trying to disconnect a slot from its signal.
I'll be a bit more verbose here, since the diff isn't very descriptive.  Also for my own memory
In using this for https://github.com/pcdshub/atef/pull/226, I ran into all manner of memory allocation errors (segfaults, bus error, malloc).  While I seemed to get a variety of errors, I mostly got things like:
```
QObject::disconnect: No such signal QObject::currentTextChanged(QString)
Segmentation fault: 11
```
We are concerned primarily with the following method: [`WeakPartialMethodSlot._method_destroyed`](https://github.com/pcdshub/pcdsutils/blob/ea6b2e2fd0d7a7ace0879bfe2390f663c7368d4f/pcdsutils/qt/callbacks.py#L83-L96)
In `WeakPartialMethodSlot`, we set up two methods to run on …
> BUG: Check for signal owner existence in WeakPartialMethodSlot teardown
